### ISSUE TITLE
Google API V.2 decomissioning

### ISSUE THREAD

**Issue by OliPicard** [cheeplusplus/groompbot#2]
Hi Andrew,

Just giving you a heads up, Google's API v2 is coming to an end. Might be a good idea to upgrade the bot to version 3. (Version 3 is built using https://developers.google.com/api-client-library/python/).

Thanks again
Oliver

**Comment by cheeplusplus** [comment]
Thanks for the warning, but the v3 API is unusable, due to caching up to 30 minutes.

The commit that enabled v3 is here: c3b89fa0fa2c2879d7044092f854d57e58818f21

**Comment by OliPicard** [comment]
Hi Andrew, Many Thanks for doing the leg work, Just out of interest is the 30 minutes per API call or the time for the upload to process over to the API? If you was to for example run the script every 24 hours would the script be useable? I'm going to try and attempt this myself. If it is I might create a forked project and when the OAuth support comes online I'll update the authentication part of the script. Once again I'll be sure to credit you as long as your Ok with this. The one thing that I have noticed is that Google claims if the call is authenticated by a developer the response times should be shorter. I'll give this a bash anyway.

I really appreciate the work you have done on this reddit bot, 

Thanks again
Oliver
